name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      clean_build:
        description: '清理构建环境'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Set up Java 17 (强制设置)
        run: |
          # 强制设置Java 17为默认Java版本
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java 17
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/temurin-17-jdk-amd64/bin/javac 17
          sudo update-alternatives --set java /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/temurin-17-jdk-amd64/bin/javac
          
          # 验证Java版本
          echo "Java版本信息："
          java -version
          javac -version
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-dev \
            build-essential \
            git \
            unzip \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            liblzma-dev
      
      - name: Set up Android environment
        run: |
          # 强制设置环境变量，确保使用Java 17
          echo "export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64" >> $HOME/.bashrc
          echo "export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk" >> $HOME/.bashrc
          echo "export ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk" >> $HOME/.bashrc
          
          # 立即应用环境变量
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk
          
          # 添加Java 17到PATH的开头
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          
          # 验证Java版本
          echo "Java版本信息："
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          
          # 创建必要的目录
          mkdir -p /home/runner/.buildozer/android/platform
          
      - name: Clean build environment
        if: ${{ github.event.inputs.clean_build == 'true' }}
        working-directory: mobile_app
        run: |
          rm -rf .buildozer
          echo "清理完成"
      
      - name: Install buildozer and dependencies
        run: |
          # 确保使用正确的Java版本
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          
          pip3 install --upgrade pip
          pip3 install --upgrade cython
          pip3 install buildozer
          echo "Buildozer安装完成"
      
      - name: Copy modules
        working-directory: mobile_app
        run: |
          # 确保使用正确的Java版本
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          
          python3 copy_modules.py || echo "模块复制可能有问题，继续构建"
      
      - name: Prepare build environment
        working-directory: mobile_app
        run: |
          # 确保使用正确的Java版本
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          
          # 检查buildozer.spec文件
          if [ ! -f buildozer.spec ]; then
            echo "错误：未找到buildozer.spec文件"
            exit 1
          fi
          
          # 显示buildozer配置
          echo "=== Buildozer配置 ==="
          cat buildozer.spec
          echo "===================="
      
      - name: Setup Android SDK with command line tools
        run: |
          # 确保使用正确的Java版本
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk
          
          # 验证Java版本
          echo "Java版本信息："
          java -version
          
          # 下载并安装Android命令行工具
          cd /home/runner/.buildozer/android/platform
          
          # 如果已经存在旧的tools目录，先备份
          if [ -d "android-sdk/tools" ]; then
            mv android-sdk/tools android-sdk/tools_backup
          fi
          
          # 创建命令行工具目录
          mkdir -p cmdline-tools/latest
          cd cmdline-tools/latest
          
          # 下载命令行工具
          if [ ! -f "commandlinetools-linux-9477386_latest.zip" ]; then
            echo "下载Android命令行工具..."
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip commandlinetools-linux-9477386_latest.zip
            rm commandlinetools-linux-9477386_latest.zip
          fi
          
          # 设置正确的权限
          chmod +x bin/*
          
          # 接受Android SDK许可
          echo "接受Android SDK许可..."
          yes | ./bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk --licenses || true
          
          # 安装platform-tools
          echo "安装platform-tools..."
          ./bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk "platform-tools" || true
      
      - name: Build APK
        working-directory: mobile_app
        run: |
          echo "开始构建APK..."
          echo "构建类型: ${{ github.event.inputs.build_type }}"
          
          # 强制设置环境变量
          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
          export PATH=/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk
          
          # 再次确认环境变量
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "PATH中的Java位置:"
          which java
          java -version
          
          # 验证Android SDK工具
          if [ -f "/home/runner/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager" ]; then
            echo "使用新的sdkmanager..."
            /home/runner/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --version
          else
            echo "使用默认sdkmanager..."
          fi
          
          # 设置超时时间
          timeout 1800 buildozer android ${{ github.event.inputs.build_type }} || BUILD_FAILED=true
          
          if [ "$BUILD_FAILED" = "true" ]; then
            echo "构建失败，尝试重新构建..."
            timeout 1800 buildozer android ${{ github.event.inputs.build_type }}
          fi
          
          echo "APK构建完成"
      
      - name: Check build results
        working-directory: mobile_app
        run: |
          echo "=== 检查构建结果 ==="
          if [ -d "bin" ]; then
            echo "bin目录内容:"
            ls -la bin/
          else
            echo "未找到bin目录"
          fi
          
          if [ -d ".buildozer" ]; then
            echo ".buildozer目录内容:"
            ls -la .buildozer/
          fi
          
          echo "=================="
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: apk-file-${{ github.event.inputs.build_type }}
          path: |
            mobile_app/bin/*.apk
            mobile_app/bin/*.aab
          retention-days: 30
      
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-logs
          path: |
            mobile_app/.buildozer/**/*.log
            mobile_app/.buildozer/android/platform/build-*/dists/*/build.log
          retention-days: 7
