# -*- mode: python ; coding: utf-8 -*-
# 传统八字命理分析系统 PyInstaller 打包配置文件

block_cipher = None

a = Analysis(
    ['bagua_clock.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('alarms.json', '.'),
        ('custom_locations.json', '.'),
        ('saved_persons', 'saved_persons'),
        ('中国命学六书', '中国命学六书'),
    ],
    hiddenimports=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtWebEngineWidgets',
        'requests',
        'pygame',
        'lunar_python',
        'lunar_python.Lunar',
        'lunar_python.Solar',
        'sxtwl',
        'sxtwl_adapter',
        'local_mingli_analyzer',
        'local_mingli_analyzer_unified',
        'classic_analyzer',
        'classic_analyzer.common',
        'classic_analyzer.caiyun',
        'classic_analyzer.geju_analyzer',
        'classic_analyzer.dayun',
        'classic_analyzer.shensha',
        'classic_analyzer.wuxing_analyzer',
        'classic_analyzer.tiaohou_analyzer',
        'classic_analyzer.yongshen_analyzer',
        'classic_analyzer.mingge_score',
        'chinese_metaphysics_library',
        'chinese_metaphysics_library.core',
        'chinese_metaphysics_library.core.data_structures',
        'chinese_metaphysics_library.core.utils',
        'chinese_metaphysics_library.yuanhaiziping',
        'chinese_metaphysics_library.yuanhaiziping.unified_analyzer',
        'chinese_metaphysics_library.santonghui',
        'chinese_metaphysics_library.santonghui.unified_analyzer',
        'chinese_metaphysics_library.santonghui.shensha_analyzer',
        'chinese_metaphysics_library.santonghui.dayun_analyzer',
        'chinese_metaphysics_library.zipingzhenquan',
        'chinese_metaphysics_library.zipingzhenquan.unified_analyzer',
        'chinese_metaphysics_library.ditiansui',
        'chinese_metaphysics_library.ditiansui.unified_analyzer',
        'chinese_metaphysics_library.qiongtongbaojian',
        'chinese_metaphysics_library.qiongtongbaojian.unified_analyzer',
        'chinese_metaphysics_library.lantaimiaoxuan',
        'chinese_metaphysics_library.lantaimiaoxuan.unified_analyzer',
        'classic_lookup_tables',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='传统八字命理分析系统',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # 禁用UPX压缩，加快打包速度
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
